services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - ./src:/app/src
      - ./style:/app/style
      - ./public:/app/public
      - ./migrations:/app/migrations
      - cargo_cache:/usr/local/cargo/registry
      - target_cache:/app/target
    command: cargo leptos watch

volumes:
  cargo_cache:
  target_cache:
